### ISSUE TITLE
[UI] Tutorial shows beneath all screens

### ISSUE THREAD

**Issue by jbktsang** [ischaaf/BuddingBudget#105]
When I open phonegap on my phone, I see "Optional/Required" text which I think corresponds to text of the tutorial. 

The tutorial is not turned on. This bug doesn't show on chrome.

**Comment by kylechu** [comment]
I'm not able to duplicate this with the newest build. Can you try pulling and testing again?

**Comment by jbktsang** [comment]
Problem fixed itself. :+1:
