### ISSUE TITLE
[Developer] Automated Build and Test

### ISSUE THREAD

**Issue by ischaaf** [ischaaf/BuddingBudget#15]

**Comment by kylechu** [comment]
How to set up an automated daily (or more frequent) build and test. For your daily build and test, you may wish to use Jenkins, CruiseControl, cron (cronic is a nice script to wrap your cron job), or similar software. Also describe how you set up your daily build and test system, and how you ensured that any failure output is emailed to your entire team. (Don't describe how you might have done it or how you plan to do it; actually do it, and describe what you did.) It is a requirement that before the due date, at least one failing daily test result is automatically emailed to the team. This obviously requires that at least some tests already exist. We do not require any successful daily tests yet.
