### ISSUE TITLE
[Developer] Bug Tracking Guide

### ISSUE THREAD

**Issue by jbktsang** [ischaaf/BuddingBudget#16]

**Comment by kylechu** [comment]
How to access the list of outstanding bugs and the list of resolved bugs, and how to resolve a bug. (If you are using an off-the-shelf bug tracking system, your instructions may be trivial, such as a URL.)
For the ZFR, your bug tracking system need not have a comprehensive list of every last bug and missing feature. However, for this and future assignments, if your customer (i.e., the course staff) runs across a problem while using your software, you will regain some credit if the bug tracking system contains a description of the problem.
