### ISSUE TITLE
[UI] Entering numbers only accepts "e"

### ISSUE THREAD

**Issue by jbktsang** [ischaaf/BuddingBudget#49]
This is in any type="number" input element

**Comment by git44** [comment]
For which file is this happening in?

**Comment by jbktsang** [comment]
For every <input id="____" data-controller="input-value" type="number" min="0">
An example would be in assets.html but it happens on every page

**Comment by jbktsang** [comment]
Code insert error, should be 
For every `<input id="texttest2" data-controller="input-value" type="number" min="0">`

**Comment by jbktsang** [comment]
Oh wait I did some quick googlework and it's[ intentional ] (http://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in)
