### ISSUE TITLE
[User] Install Guide

### ISSUE THREAD

**Issue by jbktsang** [ischaaf/BuddingBudget#6]

**Comment by kylechu** [comment]
How a user obtains and install the software. For hosted software such as a website, the installation instructions may be empty. Other specialized platforms may have their own conventions. Your instructions need to be both complete and foolproof. Indicate all steps that a user must take to install your system, on each relevant platform. Assume a user on a departmental Linux home VM, though you may additionally provide instructions for other platforms (the departmental Unix servers, non-department machine, etc.). Assume the user is a CSE undergraduate who knows nothing about your platform and toolset.
