### ISSUE TITLE
[User] Bug Report Instructions

### ISSUE THREAD

**Issue by jbktsang** [ischaaf/BuddingBudget#9]

**Comment by kylechu** [comment]
How to report a bug. This should include not just the mechanics (a URL or email address), but also what information is needed. You might want to reference a resource about how to write a good bug report: Oracle, Mozilla, Ximian, Tatham, Raymond.

Your list of bugs should ideally be publicly accessible; if so, your documentation should indicate how to access the list to prevent users from submitting duplicates.
