### ISSUE TITLE
Calculator not including income or charges in calculation?

### ISSUE THREAD

**Issue by git44** [ischaaf/BuddingBudget#97]
I set Assets to $550.
Savings to $500.
Several recurring charges, totaling at $2833. Each occurring monthly, beginning of month.
And recurring income of $3000. Occurring monthly, beginning of month.
End date is set to a month from current date. 

I expect to get an amount around $7. (((3000 - 2833) + (550 - 500))/31 = 7)
I'm actually getting $1 ($1.61 to be more precise).
1.61 is just 50/31, so income and charges are not being included in the calculation?

**Comment by kylechu** [comment]
This was actually an issue where UIView and the nextTime function disagreed on the representation of dates.
